---
- client_id: adminUI
  client_name: Omejdn Admin UI
  client_uri: http://localhost
  logo_uri: http://localhost/assets/img/fhg.jpg
  grant_types: authorization_code
  software_id: Omejdn Admin UI
  software_version: 0.0.0
  token_endpoint_auth_method: none
  redirect_uris: http://localhost
  post_logout_redirect_uris: http://localhost
  scope:
  - openid
  - omejdn:admin
  - omejdn:write
  - omejdn:read
  attributes: []
